saleor/checkout/urls.py
from django.conf.urls import url

from . import views
from .views.discount import remove_voucher_view

checkout_urlpatterns = [
    url(r"^$", views.checkout_index, name="index"),
    url(r"^start$", views.checkout_start, name="start"),
    url(
        r"^update/(?P<variant_id>\d+)/$", views.update_checkout_line, name="update-line"
    ),
    url(r"^clear/$", views.clear_checkout, name="clear"),
    url(
        r"^shipping-options/$", views.checkout_shipping_options, name="shipping-options"
    ),
    url(
        r"^shipping-address/", views.checkout_shipping_address, name="shipping-address"
    ),
    url(r"^shipping-method/", views.checkout_shipping_method, name="shipping-method"),
    url(r"^summary/", views.checkout_order_summary, name="summary"),
    url(r"^dropdown/$", views.checkout_dropdown, name="dropdown"),
    url(r"^remove_voucher/", remove_voucher_view, name="remove-voucher"),
    url(r"^login/", views.checkout_login, name="login"),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    import warnings

    try:
        import debug_toolbar
    except ImportError:
        warnings.warn(
            "The debug toolbar was not installed. Ignore the error. \
            settings.py should already have warned the user about it."
        )
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/payment/gateways/braintree/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import pgettext_lazy

from ...error_codes import PaymentErrorCode
from ...interface import PaymentData


class BraintreePaymentForm(forms.Form):
    amount = forms.DecimalField()

    # Unique transaction identifier returned by Braintree
    # for testing in the sandbox mode please refer to
    # https://developers.braintreepayments.com/reference/general/testing/python#nonces-representing-cards
    # as it's values should be hardcoded to simulate each payment gateway
    # response
    payment_method_nonce = forms.CharField()

    def __init__(self, payment_information: PaymentData, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.payment_information = payment_information
        self.fields["amount"].initial = payment_information.amount

    def clean(self):
        cleaned_data = super().clean()
        # Amount is sent client-side
        # authorizing different amount than payments' total could happen only
        # when manually adjusting the template value as we do not allow
        # partial-payments at this moment, error is returned instead.
        amount = cleaned_data.get("amount")
        if amount and amount != self.payment_information.amount:
            msg = pgettext_lazy(
                "payment error",
                "Unable to process transaction. Please try again in a moment",
            )
            raise ValidationError(msg, code=PaymentErrorCode.PAYMENT_ERROR)
        return cleaned_data

    def get_payment_token(self):
        return self.cleaned_data["payment_method_nonce"]

saleor/checkout/views/discount.py
from functools import wraps

from django.contrib import messages
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils import timezone
from django.utils.translation import pgettext
from django.views.decorators.http import require_POST

from ...discount.models import Voucher
from ..forms import CheckoutVoucherForm
from ..models import Checkout
from ..utils import (
    get_or_empty_db_checkout,
    recalculate_checkout_discount,
    remove_voucher_from_checkout,
)


def add_voucher_form(view):
    """Decorate a view injecting a voucher form and handling its submission."""

    @wraps(view)
    def func(request, checkout):
        prefix = "discount"
        data = {k: v for k, v in request.POST.items() if k.startswith(prefix)}
        voucher_form = CheckoutVoucherForm(
            data or None, prefix=prefix, instance=checkout
        )
        if voucher_form.is_bound:
            if voucher_form.is_valid():
                voucher_form.save()
                next_url = request.GET.get("next", request.META["HTTP_REFERER"])
                return redirect(next_url)
            else:
                remove_voucher_from_checkout(checkout)
                # if only discount form was used we clear post for other forms
                request.POST = {}
        else:
            recalculate_checkout_discount(checkout, request.discounts)
        response = view(request, checkout)
        if isinstance(response, TemplateResponse):
            response.context_data["voucher_form"] = voucher_form
        return response

    return func


def validate_voucher(view):
    """Decorate a view making it check whether a discount voucher is valid.

    If the voucher is invalid it will be removed and the user will be
    redirected to the checkout summary view.
    """

    @wraps(view)
    def func(request, checkout):
        if checkout.voucher_code:
            try:
                Voucher.objects.active(date=timezone.now()).get(
                    code=checkout.voucher_code
                )
            except Voucher.DoesNotExist:
                remove_voucher_from_checkout(checkout)
                msg = pgettext(
                    "Checkout warning",
                    "This voucher has expired. Please review your checkout.",
                )
                messages.warning(request, msg)
                return redirect("checkout:summary")
        return view(request, checkout)

    return func


@require_POST
@get_or_empty_db_checkout(Checkout.objects.for_display())
def remove_voucher_view(request, checkout):
    """Clear the discount and remove the voucher."""
    next_url = request.GET.get("next", request.META["HTTP_REFERER"])
    remove_voucher_from_checkout(checkout)
    return redirect(next_url)

saleor/checkout/views/shipping.py
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from ..utils import (
    get_checkout_context,
    update_shipping_address_in_anonymous_checkout,
    update_shipping_address_in_checkout,
)


def anonymous_user_shipping_address_view(request, checkout):
    """Display the shipping step for a user who is not logged in."""
    user_form, address_form, updated = update_shipping_address_in_anonymous_checkout(
        checkout, request.POST or None, request.country
    )

    if updated:
        return redirect("checkout:shipping-method")

    ctx = get_checkout_context(checkout, request.discounts)
    ctx.update({"address_form": address_form, "user_form": user_form})
    return TemplateResponse(request, "checkout/shipping_address.html", ctx)


def user_shipping_address_view(request, checkout):
    """Display the shipping step for a logged in user.

    In addition to entering a new address the user has an option of selecting
    one of the existing entries from their address book.
    """
    checkout.email = request.user.email
    checkout.save(update_fields=["email"])
    user_addresses = checkout.user.addresses.all()

    addresses_form, address_form, updated = update_shipping_address_in_checkout(
        checkout, user_addresses, request.POST or None, request.country
    )
    if updated:
        return redirect("checkout:shipping-method")

    ctx = get_checkout_context(checkout, request.discounts)
    ctx.update(
        {
            "additional_addresses": user_addresses,
            "address_form": address_form,
            "user_form": addresses_form,
        }
    )
    return TemplateResponse(request, "checkout/shipping_address.html", ctx)

saleor/checkout/views/summary.py
from django.contrib import messages
from django.db import transaction
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext

from ...account.models import Address
from ...core import analytics
from ...core.exceptions import InsufficientStock
from ...core.taxes import TaxError
from ...discount.models import NotApplicable
from ..forms import CheckoutNoteForm
from ..utils import (
    create_order,
    get_checkout_context,
    prepare_order_data,
    update_billing_address_in_anonymous_checkout,
    update_billing_address_in_checkout,
    update_billing_address_in_checkout_with_shipping,
)


@transaction.atomic()
def _handle_order_placement(request, checkout):
    """Try to create an order and redirect the user as necessary.

    This function creates an order from checkout and performs post-create actions
    such as removing the checkout instance, sending order notification email
    and creating order history events.
    """
    try:
        # Run checks an prepare the data for order creation
        order_data = prepare_order_data(
            checkout=checkout,
            tracking_code=analytics.get_client_id(request),
            discounts=request.discounts,
        )
    except InsufficientStock:
        return redirect("checkout:index")
    except NotApplicable:
        messages.warning(
            request, pgettext("Checkout warning", "Please review your checkout.")
        )
        return redirect("checkout:summary")
    except TaxError as tax_error:
        messages.warning(
            request,
            pgettext(
                "Checkout warning", "Unable to calculate taxes - %s" % str(tax_error)
            ),
        )
        return redirect("checkout:summary")

    # Push the order data into the database
    order = create_order(checkout=checkout, order_data=order_data, user=request.user)

    # remove checkout after order is created
    checkout.delete()

    # Redirect the user to the payment page
    return redirect("order:payment", token=order.token)


def summary_with_shipping_view(request, checkout):
    """Display order summary with billing forms for a logged in user.

    Will create an order if all data is valid.
    """
    note_form = CheckoutNoteForm(request.POST or None, instance=checkout)
    if note_form.is_valid():
        note_form.save()

    user_addresses = (
        checkout.user.addresses.all() if checkout.user else Address.objects.none()
    )

    addresses_form, address_form, updated = update_billing_address_in_checkout_with_shipping(  # noqa
        checkout, user_addresses, request.POST or None, request.country
    )

    if updated:
        return _handle_order_placement(request, checkout)

    ctx = get_checkout_context(checkout, request.discounts)
    ctx.update(
        {
            "additional_addresses": user_addresses,
            "address_form": address_form,
            "addresses_form": addresses_form,
            "note_form": note_form,
        }
    )
    return TemplateResponse(request, "checkout/summary.html", ctx)


def anonymous_summary_without_shipping(request, checkout):
    """Display order summary with billing forms for an unauthorized user.

    Will create an order if all data is valid.
    """
    note_form = CheckoutNoteForm(request.POST or None, instance=checkout)
    if note_form.is_valid():
        note_form.save()

    user_form, address_form, updated = update_billing_address_in_anonymous_checkout(
        checkout, request.POST or None, request.country
    )

    if updated:
        return _handle_order_placement(request, checkout)

    ctx = get_checkout_context(checkout, request.discounts)
    ctx.update(
        {"address_form": address_form, "note_form": note_form, "user_form": user_form}
    )
    return TemplateResponse(request, "checkout/summary_without_shipping.html", ctx)


def summary_without_shipping(request, checkout):
    """Display order summary for cases where shipping is not required.

    Will create an order if all data is valid.
    """
    note_form = CheckoutNoteForm(request.POST or None, instance=checkout)
    if note_form.is_valid():
        note_form.save()

    user_addresses = checkout.user.addresses.all()

    addresses_form, address_form, updated = update_billing_address_in_checkout(
        checkout, user_addresses, request.POST or None, request.country
    )

    if updated:
        return _handle_order_placement(request, checkout)

    ctx = get_checkout_context(checkout, request.discounts)
    ctx.update(
        {
            "additional_addresses": user_addresses,
            "address_form": address_form,
            "addresses_form": addresses_form,
            "note_form": note_form,
        }
    )
    return TemplateResponse(request, "checkout/summary_without_shipping.html", ctx)

saleor/checkout/views/validators.py
from functools import wraps

from django.core.exceptions import ValidationError
from django.shortcuts import redirect

from ..utils import is_valid_shipping_method


def validate_checkout(view):
    """Decorate a view making it require a non-empty checkout.

    If the checkout is empty, redirect to the checkout details.
    """

    @wraps(view)
    def func(request, checkout):
        if checkout:
            return view(request, checkout)
        return redirect("checkout:index")

    return func


def validate_shipping_address(view):
    """Decorate a view making it require a valid shipping address.

    If either the shipping address or customer email is empty, redirect to the
    shipping address step.

    Expects to be decorated with `@validate_checkout`.
    """

    @wraps(view)
    def func(request, checkout):
        if not checkout.email or not checkout.shipping_address:
            return redirect("checkout:shipping-address")
        try:
            checkout.shipping_address.full_clean()
        except ValidationError:
            return redirect("checkout:shipping-address")
        return view(request, checkout)

    return func


def validate_shipping_method(view):
    """Decorate a view making it require a shipping method.

    If the method is missing or incorrect, redirect to the shipping method
    step.

    Expects to be decorated with `@validate_checkout`.
    """

    @wraps(view)
    def func(request, checkout):
        if not is_valid_shipping_method(checkout, request.discounts):
            return redirect("checkout:shipping-method")
        return view(request, checkout)

    return func


def validate_is_shipping_required(view):
    """Decorate a view making it check if checkout needs shipping.

    If shipping is not needed, redirect to the checkout summary.

    Expects to be decorated with `@validate_checkout`.
    """

    @wraps(view)
    def func(request, checkout):
        if not checkout.is_shipping_required():
            return redirect("checkout:summary")
        return view(request, checkout)

    return func

templates/checkout/_subtotal_table.html
{% load i18n %}
{% load taxed_prices %}

{% if shipping_required %}
  <div class="table__row">
    <div class="row">
      <div class="col-8 checkout-preview__total__subtotal">
        <h3>{% trans "Subtotal" context "Order subtotal" %}</h3>
      </div>
      <div class="col-4">
        <h3 class="text-right checkout-preview-subtotal" data-value="{% price checkout_subtotal.gross html=False %}" {% if local_checkout_subtotal is not None %}data-value-local="{% price local_checkout_subtotal.gross html=False %}"{% endif %}>
          {% spaceless %}
            {% price checkout_subtotal %}
            {% if local_checkout_subtotal is not None and local_checkout_subtotal.gross %}
              <br>
              <small>
                &asymp;
                {% price local_checkout_subtotal %}
              </small>
            {% endif %}
          {% endspaceless %}
        </h3>
      </div>
    </div>
  </div>
  {% if country_form.country.field.choices %}
    <div class="last table__row checkout-preview__delivery-info">
      <div class="row">
        <div class="col-7 checkout-preview__total__subtotal deliveryform" data-csrf="{{ csrf_token }}">
          <div class="row">
            <div class="col-12 col-md-4">
              <p>{% trans "Shipping cost for:" context "Checkout shipping cost form" %}</p>
            </div>
            <div class="col-12 col-md-8">
              {{ country_form.country }}
            </div>
          </div>
        </div>
        <div class="col-5">
          <div class="row">
            <div class="col-md-12 col-12 text-right">
              <p class="checkout-preview__delivery-info__price">
                {% if shipping_price_range %}
                  {% price_range shipping_price_range %}
                {% endif %}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endif %}
<div class="checkout-preview__total">
  <div class="row">
    <div class="col-8 checkout-preview__total__subtotal">
      <h3>{% trans "Total" context "Order subtotal" %}</h3>
      <small>{% trans "Shipment and taxes calculated at checkout" context "Checkout summary text" %}</small>
    </div>
    <div class="col-4">
      {% spaceless %}
        {% if total_with_shipping %}
          <h3 class="text-right checkout-total"><span>{% price_range total_with_shipping %}</span>
            {% if local_total_with_shipping %}
              <br>
              <small>
                &asymp;
                {% price_range local_total_with_shipping %}
              </small>
            {% endif %}
          </h3>
        {% endif %}
      {% endspaceless %}
    </div>
  </div>
</div>

templates/checkout/details.html
{% extends "base.html" %}

{% load i18n %}
{% load price from taxed_prices %}
{% load static %}

{% block title %}{% trans "Checkout" context "Checkout page title" %} — {{ block.super }}{% endblock %}

{% block header %}
  <div class="container-fluid navbar__login">
    <div class="container">
      <p>{% trans "Easy and secure!" context "Checkout top message" %}</p>
    </div>
  </div>
  <header class="checkout__header">
    <div class="container">
      <a href="{% url 'home'%}">
        <svg data-src="{% static "images/logo-light.svg" %}" height="48px" width="176px" />
      </a>
      <h1>{% trans "Checkout" context "Checkout title" %}</h1>
    </div>
  </header>
{% endblock %}

{% block footer %}
{% endblock %}

{% block content %}
  <div class="row checkout">
    <div class="col-md-7">
      {% block forms %}{% endblock %}
    </div>
    <div class="col-md-5">
      <div class="checkout__review">
        <h3 class="checkout__review__tittle">{% trans "Order review" context "Order review title" %}</h3>
        {% for line, line_total in checkout_lines %}
          <div class="row">
            <div class="col-8">
              <p><strong>{{ line.variant.product.translated }}</strong> x {{ line.quantity }}<br>
                <span class="checkout__review__variant">{{ line.variant.translated }}</span></p>
            </div>
            <div class="col-4">
              <p class="float-right">
                {% price line_total %}
              </p>
            </div>
          </div>
        {% endfor %}
        <div class="row checkout__review__section">
          <div class="col-8">
            <p>{% trans "Subtotal" context "Order review section" %}</p>
          </div>
          <div class="col-4">
            <p class="float-right">
              {% price checkout_subtotal %}
            </p>
          </div>
        </div>
        <div class="row checkout__review__section">
          <div class="col-8">
            <p>{% trans "Shipment" context "Order review section" %}</p>
          </div>
          <div class="col-4">
            <p class="float-right">
              {% if checkout.shipping_method %}
                {% price checkout_shipping_price %}
              {% else %}
                &mdash;
              {% endif %}
            </p>
          </div>
        </div>
        {% if checkout_are_taxes_handled %}
          <div class="row checkout__review__section">
            <div class="col-8">
              {% if site.settings.display_gross_prices %}
                <p>{% trans "Taxes (included)" context "Order review section title" %}</p>
              {% else %}
                <p>{% trans "Taxes" context "Order review section title" %}</p>
              {% endif %}
            </div>
            <div class="col-4">
              <p class="float-right">{% price checkout_total.tax %}</p>
            </div>
          </div>
        {% endif %}
        <div class="row checkout__review__section">
          <div class="col-12">
            <h3>{% trans "Promo code" context "Order review section title" %}</h3>
            {% include "checkout/snippets/voucher_form.html" with checkout=checkout form=voucher_form %}
          </div>
        </div>
        <div class="row checkout__review__section">
          <div class="col-8">
            <h3>{% trans "Total" context "Order review section title" %}</h3>
          </div>
          <div class="col-4">
            <h3 class="float-right">{% price checkout_total.gross %}</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/checkout/index.html
{% extends "base.html" %}
{% load i18n %}
{% load get_product_image_thumbnail from product_images %}
{% load price from taxed_prices %}
{% load static %}

{% block title %}{% trans "Your cart" context "Checkout page title" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
  <ul class="breadcrumbs list-unstyled">
    <li><a href="{% url 'home' %}">{% trans "Home" context "Main navigation item" %}</a></li>
    <li><a rel="nofollow" href="{% url 'checkout:index' %}">{% trans "Cart" context "Checkout breadcrumb" %}</a></li>
  </ul>
{% endblock breadcrumb %}

{% block meta_tags %}
  <meta name="robots" content="nofollow">
{% endblock meta_tags %}

{% block content %}
  <div class="alert alert-success remove-product-alert d-none">
    {% trans "Product has been removed from checkout" context "Checkout message" %}
    <button type="button" class="close close-msg" aria-hidden="true">&times;</button>
  </div>
  <div class="checkout-preview">
    {% if checkout_lines %}
      <div class="table__header d-none d-md-block">
        <div class="row">
          <div class="col-md-7">
            <small>{% trans "Product" context "Checkout table header" %}</small>
          </div>
          <div class="col-md-3">
            <small>{% trans "Quantity" context "Checkout table header" %}</small>
          </div>
          <div class="col-md-2 text-right">
            <small>{% trans "Price" context "Checkout table header" %}</small>
          </div>
        </div>
      </div>
      {% for line in checkout_lines %}
        <div class="checkout-preview__line{% if forloop.last %} last{% endif %} table__row">
          <div class="row">
            <div class="col-7 checkout-preview__line__product">
              <a class="link--clean" href="{{ line.variant.get_absolute_url }}">
                <img class="lazyload lazypreload" data-src="{% get_product_image_thumbnail line.variant.get_first_image method="thumbnail" size=60 %}"
                     data-srcset="{% get_product_image_thumbnail line.variant.get_first_image method="thumbnail" size=60 %} 1x, {% get_product_image_thumbnail line.variant.get_first_image method="thumbnail" size=120 %} 2x"
                     alt="">
                <p>{{ line.variant.product.translated }}<br><small>{{ line.variant.translated }}</small></p>
              </a>
            </div>
            <div class="col-5">
              <div class="row">
                <div class="checkout-preview__line__quantity col-md-7 col-12">
                  <form role="form" action="{% url "checkout:update-line" variant_id=line.variant.pk %}" method="post" class="form-checkout">
                    <div class="{% if form.quantity.errors %} has-error{% endif %}" tabindex="-1">
                      {{ line.form.quantity }}
                    </div>
                    {% csrf_token %}
                  </form>
                  <span class="checkout-preview-item-delete">
                    <svg data-src="{% static "images/delete.svg" %}" height="20px" width="20px" />
                  </span>
                  <small class="checkout-preview__line__quantity-error text-danger"></small>
                </div>
                <div class="checkout-preview-item-price col-md-5 col-12" data-product-id="{{ line.variant.pk }}">
                  <p class="text-right">
                    {% price line.get_total %}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      <div class="checkout__subtotal">
        {% include 'checkout/_subtotal_table.html' %}
      </div>
      <div class="row">
        <div class="col-md-12">
            <a href="{% url "checkout:login" %}" class="btn btn-primary float-right checkout-preview__submit">
            {% trans "Checkout" context "Checkout primary action" %}
          </a>
            <button class="btn secondary float-right checkout-preview__clear" data-action="{% url 'checkout:clear' %}">
            {% trans "Clear cart" context "checkout page: secondary action, empty the checkout" %}
          </button>
        </div>
      </div>
    {% else %}
      <div class="checkout-preview__empty">
        <img class="lazyload lazypreload" data-src="{% static 'images/empty-checkout-bg.png' %}" data-srcset="{% static 'images/empty-checkout-bg.png' %} 1x, {% static 'images/empty-checkout-bg2x.png' %} 2x">
        <h2>{% trans "There are no products in your shopping cart." context "Empty checkout message" %}</h2>
        <a href="{% url 'home' %}" class="btn btn-primary">{% trans "Check out our sales" context "Empty checkout link" %}</a>
      </div>
    {% endif %}
  </div>
{% endblock content %}

templates/checkout/login.html
{% extends "checkout/details.html" %}
{% load static %}
{% load i18n %}
{% load placeholder %}

{% block title %}{% trans "Login" context "Checkout login page title" %} — {{ block.super }}{% endblock %}

{% block content %}
  <div class="row checkout__login">
    <div class="col-12 col-md-6">
      <div class="checkout__login__continue">
        <h3>{% trans "New customer?" context "Checkout login page title" %}</h3>
        <img class="checkout-pirate lazyload lazypreload"
             data-src="{% static 'images/login-bg.png' %}"
             data-srcset="{% static 'images/login-bg.png' %} 1x, {% static 'images/login-bg2x.png' %} 2x">
        <p>
          <a href="{% url 'checkout:start' %}" class="btn secondary narrow">
            {% trans "Continue" context "Checkout login page new users action" %}
          </a>
        </p>
        <small>{% trans "Registration is not required!" context "Checkout login page new users message" %}</small>
      </div>
    </div>
    <div class="col-12 col-md-6 checkout__login__form">
      {% url "checkout:start" as checkout_url %}
      <h3>{% trans "Existing customer? Log in." context "Checkout login form title" %}</h3>
      {% include "account/partials/login_form.html" with REDIRECT_FIELD_VALUE=checkout_url %}
    </div>
  </div>
{% endblock %}

templates/checkout/payment.html
{% extends "checkout/details.html" %}
{% load i18n %}
{% load bootstrap_form from bootstrap4 %}


{% block forms %}
  <form method="post" novalidate>
    {% csrf_token %}
    <h1>{% trans "Payment" context "Checkout payment title" %}</h1>
    {% bootstrap_form payment_form %}
    {% bootstrap_form billing_address_form %}
    <button type="submit" class="btn btn-primary">
      {% trans "Place order" context "Checkout payment primary action" %}
    </button>
  </form>
{% endblock forms %}

templates/checkout/shipping_address.html
{% extends "checkout/details.html" %}
{% load i18n %}
{% load bootstrap_form from bootstrap4 %}

{% block forms %}
  <form method="post" novalidate class="checkout__shipping">
    {% csrf_token %}
    <h2>{% trans "Shipping address" context "Checkout shipping address title" %}</h2>
    
    <div class="checkout__addresses{{ request.user.is_authenticated|yesno:",--full-width" }}">
      {% if request.user.is_authenticated %}
        {% include "checkout/snippets/addresses_form.html" with addresses_form=user_form addresses=additional_addresses address_form=address_form only %}
      {% else %}
        {% bootstrap_form user_form %}
        {% include "account/snippets/address_form.html" with address_form=address_form only %}
      {% endif %}
    </div>

    <div class="checkout__addresses">
      <button type="submit" class="btn btn-primary">
        {% trans "Continue" context "Checkout shipping address primary action" %}
      </button>
    </div>
  </form>
{% endblock %}