saleor/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views

urlpatterns = [
    url(r"^%s/$" % (TOKEN_PATTERN,), views.details, name="details"),
    url(r"^%s/payment/$" % (TOKEN_PATTERN,), views.payment, name="payment"),
    url(
        r"^%s/payment/(?P<gateway>[-\w]+)/$" % (TOKEN_PATTERN,),
        views.start_payment,
        name="payment",
    ),
    url(
        r"^%s/cancel-payment/$" % (TOKEN_PATTERN,),
        views.cancel_payment,
        name="cancel-payment",
    ),
    url(
        r"^%s/payment-success/$" % (TOKEN_PATTERN,),
        views.payment_success,
        name="payment-success",
    ),
    url(
        r"^%s/checkout-success/$" % (TOKEN_PATTERN,),
        views.checkout_success,
        name="checkout-success",
    ),
    url(
        r"^%s/attach/$" % (TOKEN_PATTERN,),
        views.connect_order_with_user,
        name="connect-order-with-user",
    ),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    import warnings

    try:
        import debug_toolbar
    except ImportError:
        warnings.warn(
            "The debug toolbar was not installed. Ignore the error. \
            settings.py should already have warned the user about it."
        )
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/order/models.py
from decimal import Decimal
from operator import attrgetter
from uuid import uuid4

from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import F, Max, Sum
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import pgettext_lazy
from django_measurement.models import MeasurementField
from django_prices.models import MoneyField, TaxedMoneyField
from measurement.measures import Weight
from prices import Money

from ..account.models import Address
from ..core.models import ModelWithMetadata
from ..core.taxes import zero_money, zero_taxed_money
from ..core.utils.json_serializer import CustomJsonEncoder
from ..core.weight import WeightUnits, zero_weight
from ..discount.models import Voucher
from ..giftcard.models import GiftCard
from ..payment import ChargeStatus, TransactionKind
from ..shipping.models import ShippingMethod
from . import FulfillmentStatus, OrderEvents, OrderStatus


class OrderQueryset(models.QuerySet):
    def confirmed(self):
        """Return non-draft orders."""
        return self.exclude(status=OrderStatus.DRAFT)

    def drafts(self):
        """Return draft orders."""
        return self.filter(status=OrderStatus.DRAFT)

    def ready_to_fulfill(self):
        """Return orders that can be fulfilled.

        Orders ready to fulfill are fully paid but unfulfilled (or partially
        fulfilled).
        """
        statuses = {OrderStatus.UNFULFILLED, OrderStatus.PARTIALLY_FULFILLED}
        qs = self.filter(status__in=statuses, payments__is_active=True)
        qs = qs.annotate(amount_paid=Sum("payments__captured_amount"))
        return qs.filter(total_gross_amount__lte=F("amount_paid"))

    def ready_to_capture(self):
        """Return orders with payments to capture.

        Orders ready to capture are those which are not draft or canceled and
        have a preauthorized payment. The preauthorized payment can not
        already be partially or fully captured.
        """
        qs = self.filter(
            payments__is_active=True, payments__charge_status=ChargeStatus.NOT_CHARGED
        )
        qs = qs.exclude(status={OrderStatus.DRAFT, OrderStatus.CANCELED})
        return qs.distinct()


class Order(ModelWithMetadata):
    created = models.DateTimeField(default=now, editable=False)
    status = models.CharField(
        max_length=32, default=OrderStatus.UNFULFILLED, choices=OrderStatus.CHOICES
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="orders",
        on_delete=models.SET_NULL,
    )
    language_code = models.CharField(max_length=35, default=settings.LANGUAGE_CODE)
    tracking_client_id = models.CharField(max_length=36, blank=True, editable=False)
    billing_address = models.ForeignKey(
        Address, related_name="+", editable=False, null=True, on_delete=models.SET_NULL
    )
    shipping_address = models.ForeignKey(
        Address, related_name="+", editable=False, null=True, on_delete=models.SET_NULL
    )
    user_email = models.EmailField(blank=True, default="")

    currency = models.CharField(
        max_length=settings.DEFAULT_CURRENCY_CODE_LENGTH,
        default=settings.DEFAULT_CURRENCY,
    )

    shipping_method = models.ForeignKey(
        ShippingMethod,
        blank=True,
        null=True,
        related_name="orders",
        on_delete=models.SET_NULL,
    )
    shipping_method_name = models.CharField(
        max_length=255, null=True, default=None, blank=True, editable=False
    )

    shipping_price_net_amount = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=0,
        editable=False,
    )
    shipping_price_net = MoneyField(
        amount_field="shipping_price_net_amount", currency_field="currency"
    )

    shipping_price_gross_amount = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=0,
        editable=False,
    )
    shipping_price_gross = MoneyField(
        amount_field="shipping_price_gross_amount", currency_field="currency"
    )

    shipping_price = TaxedMoneyField(
        net_amount_field="shipping_price_net_amount",
        gross_amount_field="shipping_price_gross_amount",
        currency_field="currency",
    )

    token = models.CharField(max_length=36, unique=True, blank=True)
    # Token of a checkout instance that this order was created from
    checkout_token = models.CharField(max_length=36, blank=True)

    total_net_amount = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=0,
    )
    total_net = MoneyField(amount_field="total_net_amount", currency_field="currency")

    total_gross_amount = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=0,
    )
    total_gross = MoneyField(
        amount_field="total_gross_amount", currency_field="currency"
    )

    total = TaxedMoneyField(
        net_amount_field="total_net_amount",
        gross_amount_field="total_gross_amount",
        currency_field="currency",
    )

    voucher = models.ForeignKey(
        Voucher, blank=True, null=True, related_name="+", on_delete=models.SET_NULL
    )
    gift_cards = models.ManyToManyField(GiftCard, blank=True, related_name="orders")
    discount_amount = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=0,
    )
    discount = MoneyField(amount_field="discount_amount", currency_field="currency")
    discount_name = models.CharField(max_length=255, default="", blank=True)
    translated_discount_name = models.CharField(max_length=255, default="", blank=True)
    display_gross_prices = models.BooleanField(default=True)
    customer_note = models.TextField(blank=True, default="")
    weight = MeasurementField(
        measurement=Weight, unit_choices=WeightUnits.CHOICES, default=zero_weight
    )
    objects = OrderQueryset.as_manager()

    class Meta:
        ordering = ("-pk",)
        permissions = (
            (
                "manage_orders",
                pgettext_lazy("Permission description", "Manage orders."),
            ),
        )

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = str(uuid4())
        return super().save(*args, **kwargs)

    def is_fully_paid(self):
        total_paid = self._total_paid()
        return total_paid.gross >= self.total.gross

    def is_partly_paid(self):
        total_paid = self._total_paid()
        return total_paid.gross.amount > 0

    def get_customer_email(self):
        return self.user.email if self.user else self.user_email

    def _total_paid(self):
        # Get total paid amount from partially charged,
        # fully charged and partially refunded payments
        payments = self.payments.filter(
            charge_status__in=[
                ChargeStatus.PARTIALLY_CHARGED,
                ChargeStatus.FULLY_CHARGED,
                ChargeStatus.PARTIALLY_REFUNDED,
            ]
        )
        total_captured = [payment.get_captured_amount() for payment in payments]
        total_paid = sum(total_captured, zero_taxed_money())
        return total_paid

    def _index_billing_phone(self):
        return self.billing_address.phone

    def _index_shipping_phone(self):
        return self.shipping_address.phone

    def __iter__(self):
        return iter(self.lines.all())

    def __repr__(self):
        return "<Order #%r>" % (self.id,)

    def __str__(self):
        return "#%d" % (self.id,)

    def get_absolute_url(self):
        return reverse("order:details", kwargs={"token": self.token})

    def get_last_payment(self):
        return max(self.payments.all(), default=None, key=attrgetter("pk"))

    def get_payment_status(self):
        last_payment = self.get_last_payment()
        if last_payment:
            return last_payment.charge_status
        return ChargeStatus.NOT_CHARGED

    def get_payment_status_display(self):
        last_payment = self.get_last_payment()
        if last_payment:
            return last_payment.get_charge_status_display()
        return dict(ChargeStatus.CHOICES).get(ChargeStatus.NOT_CHARGED)

    def is_pre_authorized(self):
        return (
            self.payments.filter(
                is_active=True, transactions__kind=TransactionKind.AUTH
            )
            .filter(transactions__is_success=True)
            .exists()
        )

    @property
    def quantity_fulfilled(self):
        return sum([line.quantity_fulfilled for line in self])

    def is_shipping_required(self):
        return any(line.is_shipping_required for line in self)

    def get_subtotal(self):
        subtotal_iterator = (line.get_total() for line in self)
        return sum(subtotal_iterator, zero_taxed_money())

    def get_total_quantity(self):
        return sum([line.quantity for line in self])

    def is_draft(self):
        return self.status == OrderStatus.DRAFT

    def is_open(self):
        statuses = {OrderStatus.UNFULFILLED, OrderStatus.PARTIALLY_FULFILLED}
        return self.status in statuses

    def can_cancel(self):
        return self.status not in {OrderStatus.CANCELED, OrderStatus.DRAFT}

    def can_capture(self, payment=None):
        if not payment:
            payment = self.get_last_payment()
        if not payment:
            return False
        order_status_ok = self.status not in {OrderStatus.DRAFT, OrderStatus.CANCELED}
        return payment.can_capture() and order_status_ok

    def can_void(self, payment=None):
        if not payment:

saleor/order/forms.py
from django import forms
from django.utils.functional import lazy
from django.utils.translation import pgettext_lazy

from ..account.forms import SignupForm
from ..payment import gateway
from ..payment.models import Payment
from . import events
from .models import Order


def get_gateways():
    gateways = [
        (gtw["name"], gtw["name"].capitalize() + " gateway")
        for gtw in gateway.list_gateways()
    ]
    return gateways


class PaymentsForm(forms.Form):
    gateway = forms.ChoiceField(
        label=pgettext_lazy("Payments form label", "Payment Method"),
        choices=lazy(get_gateways, tuple),
        widget=forms.RadioSelect,
    )


class PaymentDeleteForm(forms.Form):
    payment_id = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop("order")
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        payment_id = cleaned_data.get("payment_id")
        payment = Payment.objects.filter(is_active=True, id=payment_id).first()
        if not payment:
            self._errors["number"] = self.error_class(
                [pgettext_lazy("Payment delete form error", "Payment does not exist")]
            )
        elif not payment.can_void():
            self._errors["number"] = self.error_class(
                [
                    pgettext_lazy(
                        "Payment delete form error", "Payment cannot be cancelled."
                    )
                ]
            )
        else:
            cleaned_data["payment"] = payment
        return cleaned_data

    def save(self):
        payment = self.cleaned_data["payment"]
        gateway.void(payment)


class PasswordForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget = forms.HiddenInput()


class CustomerNoteForm(forms.ModelForm):
    customer_note = forms.CharField(
        max_length=250,
        required=False,
        strip=True,
        label=False,
        widget=forms.Textarea({"rows": 3}),
    )

    class Meta:
        model = Order
        fields = ["customer_note"]

    def save(self, *, user, commit=True):
        events.order_note_added_event(
            order=self.instance, user=user, message=self.instance.customer_note
        )
        return super().save(commit)

saleor/payment/gateways/braintree/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import pgettext_lazy

from ...error_codes import PaymentErrorCode
from ...interface import PaymentData


class BraintreePaymentForm(forms.Form):
    amount = forms.DecimalField()

    # Unique transaction identifier returned by Braintree
    # for testing in the sandbox mode please refer to
    # https://developers.braintreepayments.com/reference/general/testing/python#nonces-representing-cards
    # as it's values should be hardcoded to simulate each payment gateway
    # response
    payment_method_nonce = forms.CharField()

    def __init__(self, payment_information: PaymentData, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.payment_information = payment_information
        self.fields["amount"].initial = payment_information.amount

    def clean(self):
        cleaned_data = super().clean()
        # Amount is sent client-side
        # authorizing different amount than payments' total could happen only
        # when manually adjusting the template value as we do not allow
        # partial-payments at this moment, error is returned instead.
        amount = cleaned_data.get("amount")
        if amount and amount != self.payment_information.amount:
            msg = pgettext_lazy(
                "payment error",
                "Unable to process transaction. Please try again in a moment",
            )
            raise ValidationError(msg, code=PaymentErrorCode.PAYMENT_ERROR)
        return cleaned_data

    def get_payment_token(self):
        return self.cleaned_data["payment_method_nonce"]

templates/order/checkout_success.html
{% extends 'base.html' %}

{% load bootstrap_form from bootstrap4 %}
{% load static %}
{% load i18n %}
{% load placeholder %}

{% block title %}{% trans "Thank you" context "Checkout success page title" %} — {{ block.super }}{% endblock %}


{% block content %}
  <div class="row checkout__thankyoupage">
    <div class="col-xl-10 m-auto">
      <img class="checkout__thankyoupage__parrot lazyload lazypreload" data-src="{% static 'images/confirm-order-bg.png' %}"
           srcset="{% static 'images/confirm-order-bg.png' %} 1x, {% static 'images/confirm-order-bg2x.png' %} 2x">
      <h1>{% blocktrans trimmed with order_url=order.get_absolute_url context "Checkout title" %}
          Thank you for your <a href="{{ order_url }}">order</a>!
      {% endblocktrans %}</h1>

        <p>{% blocktrans trimmed with order_url=order.get_absolute_url context "Checkout text" %}
          We've sent a confirmation email with details to <span>{{ email }}</span>.<br>
          In case of any problems or questions please contact us.
        {% endblocktrans %}</p>
    </div>
    <div class="m-auto">
      <img class="checkout-pirate lazyload lazypreload" data-src="{% static 'images/checkout-bg.png' %}"
           srcset="{% static 'images/checkout-bg.png' %} 1x, {% static 'images/checkout-bg2x.png' %} 2x">
      <p><a href="{% url 'home' %}" class="btn secondary">
          {% trans "Continue shopping" context "Checkout secondary action" %}
      </a></p>
    </div>
  </div>
{% endblock %}

templates/order/checkout_success_anonymous.html
{% extends 'base.html' %}

{% load bootstrap_form from bootstrap4 %}
{% load static %}
{% load i18n %}
{% load placeholder %}

{% block title %}{% trans "Thank you" context "Checkout success page title" %} — {{ block.super }}{% endblock %}


{% block content %}
  <div class="row checkout__thankyoupage">
    <div class="col-xl-10 m-auto">
      <img class="checkout__thankyoupage__parrot lazyload lazypreload" data-src="{% static 'images/confirm-order-bg.png' %}"
           data-srcset="{% static 'images/confirm-order-bg.png' %} 1x, {% static 'images/confirm-order-bg2x.png' %} 2x">
      <h1>{% blocktrans trimmed with order_url=order.get_absolute_url context "Checkout title" %}
          Thank you for your <a href="{{ order_url }}">order</a>!
      {% endblocktrans %}</h1>

      <p>{% blocktrans trimmed with order_url=order.get_absolute_url context "Checkout text" %}
        We've sent a confirmation email with details to <span>{{ email }}</span>.<br>
        In case of any problems or questions please contact us.
      {% endblocktrans %}</p>
      <div class="row checkout__thankyoupage__form">
        <div class="col-md-6 push-md-6">
          {% if login_form is not None %}
            <p>{% blocktrans trimmed context "Checkout text" %}
              It looks like you already are our customer! <br>
              Please log in to connect order with your account.
            {% endblocktrans %}</p>
            {% url "order:connect-order-with-user" token=order.token as attach_url %}
            {% include "account/partials/login_form.html" with REDIRECT_FIELD_VALUE=attach_url form=login_form %}
          {% else %}
            <form method="post" action="" novalidate>
              {% csrf_token %}
              <fieldset>
                <h3>{% trans "Why not to create an account" context "Checkout title" %}</h3>
                <p>{% blocktrans trimmed %}
                  Make your shopping experience even better!
                  Save your shipping and payment details for faster checkout.
                {% endblocktrans %}</p>
                {% bootstrap_form form %}
              </fieldset>
              <div class="row login__btn-group">
                <div class="col-12">
                  <button class="btn btn-primary">
                    {% trans "Create an account" context "Checkout primary action" %}
                  </button>
                </div>
              </div>
            </form>
          {% endif %}
        </div>
        <div class="col-md-6 pull-md-6">
          <img class="checkout-pirate lazyload lazypreload" data-src="{% static 'images/checkout-bg.png' %}"
               data-srcset="{% static 'images/checkout-bg.png' %} 1x, {% static 'images/checkout-bg2x.png' %} 2x">
          <p><a href="{% url 'home' %}" class="btn secondary">
              {% trans "Continue shopping" context "Checkout secondary action" %}
          </a></p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/order/details.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load bootstrap_form from bootstrap4 %}

{% block title %}
  {% blocktrans trimmed context "Order details page title" %}
    Order {{ order }}
  {% endblocktrans %} — {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  {% if order.user == user %}
    <ul class="breadcrumbs list-unstyled">
      <li>
        <a href="{% url 'home'%}">
          {% trans "Home" context "Main navigation item" %}
        </a>
      </li>
      <li>
        <a href="{% url "account:details" %}">
          {% trans "Your account" context "Main navigation item" %}
        </a>
      </li>
      <li>
        <a href="{{ order.get_absolute_url }}">
          {% blocktrans trimmed context "Order details breadcrumb" %}
            Order {{ order }}
          {% endblocktrans %}
        </a>
      </li>
    </ul>
  {% endif %}
{% endblock breadcrumb %}

{% block meta_tags %}
  <meta name="robots" content="noindex, nofollow">
{% endblock meta_tags %}

{% block content %}
  {# This view is available by just knowing url,          #}
  {# so we don't show all details (like shipping address) #}
  {# unless current user is owner of the order.           #}

  <div class="row order-details">
    <div class="col-lg-10 m-auto">
      <h2 class="order-details__header">
        {% blocktrans trimmed with payment_status=order.get_payment_status_display order_status=order.get_status_display context "Order detail text" %}
          Order {{ order }}: {{ payment_status }} & {{ order_status }}
        {% endblocktrans %}
      </h2>
      {% if not order.is_partly_paid %}
        {% if order.is_pre_authorized %}
          <a href="{% url "order:payment" token=order.token %}" class="btn btn-link">
            {% trans "Payment details" context "Order details link text" %}
          </a>
        {% else %}
          <a href="{% url "order:payment" token=order.token %}" class="btn btn-primary">
            {% trans "Pay for order" context "Order details primary action" %}
          </a>
        {% endif %}
      {% endif %}
      {% include "order/_ordered_items_table.html" %}
      <div class="order-notes">
      {% if order.customer_note %}
        <h2 class="order-notes__header">{% trans "Your note" context "Customer order note" %}</h2>
        <p>{{ order.customer_note }}</p>
      {% endif %}
      {% if order.is_open and not order.customer_note %}
        <form method="post" class="form-group">
          {% csrf_token %}
          <h2>{% trans "Add a note to your order" context "Order note title" %}</h2>
          {% bootstrap_form note_form display_labels=False %}
          <input type="submit" value="{% trans 'Submit note' context 'Customer panel - order details: add note submit button' %}" class="btn btn-primary" />
        </form>
      {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/order/payment.html
{% extends "base.html" %}

{% load bootstrap_form from bootstrap4 %}
{% load i18n %}
{% load static %}

{% block title %}
  {% blocktrans trimmed context "Payment details page title" %}
    Pay for order {{ order }}
  {% endblocktrans %} — {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  {% if order.user == user %}
    <ul class="breadcrumbs list-unstyled">
      <li>
        <a href="{% url 'home' %}">
          {% trans "Home" context "Main navigation item" %}
        </a>
      </li>
      <li>
        <a href="{% url "account:details" %}">
          {% trans "Your account" context "Main navigation item" %}
        </a>
      </li>
      <li>
        <a href="{{ order.get_absolute_url }}">
          {% blocktrans trimmed context "Payment details breadcrumb" %}
            Order {{ order }}
          {% endblocktrans %}
        </a>
      </li>
    </ul>
  {% endif %}
{% endblock breadcrumb %}

{% block content %}
  <div class="row checkout">
    <div class="col-lg-10 m-auto checkout__payment">
      {% if order.user == user or not order.is_fully_paid %}
        {% if not order.is_fully_paid and order.billing_address %}
          {% if waiting_payment %}
            <h1>
              {% trans "Payment pending" context "Payment details title" %}
            </h1>
            <form method="post" action="{% url 'order:cancel-payment' token=order.token %}" class="checkout-form">
              {% csrf_token %}
              <p>{% blocktrans trimmed context "Payment pending text" %}
                We are currently waiting for an external service to authorize
                your payment for this order.
              {% endblocktrans %}</p>
              <p>{% trans "Current status:" context "Payment status text" %}
                <br>
                <span class="label label-default">
                {{ waiting_payment.get_charge_status_display }}
                </span>
              </p>
              <p>{%  blocktrans trimmed context "Payment pending text" %}
                Unless you are absolutely sure that the process will not complete
                (for example you have closed the browser window before paying),
                you should wait before attempting a new payment.
                Please be warned that if you try again and the previous
                transaction succeeds you might end up being charged twice.
              {% endblocktrans %}</p>
              {% bootstrap_form waiting_payment_form %}
              <button type="submit" class="btn danger">
                {% trans "I understand, allow me to pay again" context "Payment pending action" %}
              </button>
            </form>
          {% elif payment_form %}
            <h1>
              {% blocktrans trimmed context "Payment details title" %}
                Pay for order {{ order }}
              {% endblocktrans %}
            </h1>
            <h3>
              <b>{% trans "Choose payment method" %}</b>
            </h3>
            <div class="checkout__payment-form">
              <form method="post" action="{% url "order:payment" token=order.token %}" class="payment-form radio">
                {% csrf_token %}
                {% for choice in payment_form.gateway %}
                  <div class="radio checkout__payment-form__choice">
                    <label>
                      <div class="card card-default">
                        <div class="card-body">
                          <strong>
                            {{choice}}
                          </strong>
                        </div>
                      </div>
                    </label>
                  </div>
                {% endfor %}
                {% block form_submit %}
                  <button type="submit" class="btn btn-primary">
                    {% trans "Proceed to payment" context "Payment details primary action" %}
                  </button>
                {% endblock %}
              </form>
            </div>
          {% else %}
            <p>{% trans "You've authorized transaction. Order is in processing" context "Payment details text" %}</p>
          {% endif %}
        {% endif %}
      {% endif %}
      {% include 'order/_ordered_items_table.html' %}
    </div>
  </div>
{% endblock content %}